"""initial_schema

Revision ID: cfd9630f761f
Revises: 
Create Date: 2026-06-04 19:55:18.957288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfd9630f761f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=128), nullable=False),
    sa.Column('api_key_hash', sa.String(length=128), nullable=False),
    sa.Column('api_key_last4', sa.String(length=4), nullable=False),
    sa.Column('helm_release', sa.String(length=255), nullable=False),
    sa.Column('helm_command', sa.Text(), nullable=False),
    sa.Column('provisioning_state', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_credentials_user_id'), 'api_credentials', ['user_id'], unique=True)
    op.create_table('behavioral_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_hash', sa.String(length=64), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('hour_decimal', sa.Float(), nullable=False),
    sa.Column('losing_streak', sa.Integer(), nullable=False),
    sa.Column('drawdown_state', sa.Float(), nullable=False),
    sa.Column('lot_deviation', sa.Float(), nullable=False),
    sa.Column('revenge_timer', sa.Float(), nullable=False),
    sa.Column('lots', sa.Float(), nullable=False),
    sa.Column('rr_ratio', sa.Float(), nullable=False),
    sa.Column('realized_vol_20', sa.Float(), nullable=False),
    sa.Column('trend_momentum', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('size_multiplier', sa.Float(), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('user_feedback_label', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavioral_logs_audit_id'), 'behavioral_logs', ['audit_id'], unique=False)
    op.create_index(op.f('ix_behavioral_logs_user_hash'), 'behavioral_logs', ['user_hash'], unique=False)
    op.create_table('onboarding_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('broker_server', sa.String(length=255), nullable=False),
    sa.Column('account_id', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('min_trades', sa.Integer(), nullable=False),
    sa.Column('model_s3_key', sa.String(length=255), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_jobs_job_id'), 'onboarding_jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_onboarding_jobs_state'), 'onboarding_jobs', ['state'], unique=False)
    op.create_index(op.f('ix_onboarding_jobs_user_id'), 'onboarding_jobs', ['user_id'], unique=False)
    op.create_table('risk_audits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('size_multiplier', sa.Float(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('top_reason', sa.String(length=255), nullable=True),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_audits_user_id'), 'risk_audits', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('broker_server', sa.String(length=255), nullable=True),
    sa.Column('account_id', sa.String(length=128), nullable=True),
    sa.Column('vault_path', sa.String(length=255), nullable=True),
    sa.Column('model_s3_key', sa.String(length=255), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('is_baseline_ready', sa.Boolean(), nullable=False),
    sa.Column('maturity_state', sa.String(length=32), nullable=False),
    sa.Column('enforce_mode', sa.Boolean(), nullable=False),
    sa.Column('model_level', sa.Integer(), nullable=False),
    sa.Column('feedback_score', sa.Float(), nullable=False),
    sa.Column('capital_protected', sa.Float(), nullable=False),
    sa.Column('initial_parameters', sa.JSON(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_risk_audits_user_id'), table_name='risk_audits')
    op.drop_table('risk_audits')
    op.drop_index(op.f('ix_onboarding_jobs_user_id'), table_name='onboarding_jobs')
    op.drop_index(op.f('ix_onboarding_jobs_state'), table_name='onboarding_jobs')
    op.drop_index(op.f('ix_onboarding_jobs_job_id'), table_name='onboarding_jobs')
    op.drop_table('onboarding_jobs')
    op.drop_index(op.f('ix_behavioral_logs_user_hash'), table_name='behavioral_logs')
    op.drop_index(op.f('ix_behavioral_logs_audit_id'), table_name='behavioral_logs')
    op.drop_table('behavioral_logs')
    op.drop_index(op.f('ix_api_credentials_user_id'), table_name='api_credentials')
    op.drop_table('api_credentials')
    # ### end Alembic commands ###
